#version: 2
#updates:
#  - package-ecosystem: "github-actions"
#    directory: "/"
#    schedule:
#      interval: "daily"

#  - package-ecosystem: "composer"
#    directory: "/"
#    schedule:
#      interval: "weekly"
#    reviewers:
#      - "fguillot"
#    assignees:
#      - "fguillot"

#  - package-ecosystem: "docker"
#    directory: "/"
#    schedule:
#      interval: "weekly"
#    reviewers:
#      - "fguillot"
#    assignees:
#      - "fguillot"
