apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}  # First container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: {{ include "name" . }}-content
              mountPath: /var/www/app
      volumes:
        - name: {{ include "name" . }}-content
          persistentVolumeClaim:
            claimName: {{ include "name" . }}-pvc

