apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "name" . }}
        release: {{ .Release.Name }}
    spec:
      securityContext:
        fsGroup: 101
        runAsGroup: 101
        runAsUser: 100
      volumes:
      - name: {{ include "name" . }}-volume
        persistentVolumeClaim:
          claimName: {{ include "name" . }}-pvc
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          volumeMounts:
          - name: {{ include "name" . }}-volume
            mountPath: /var/www/
          allowPrivilegeEscalation: true

        



