apiVersion: v1
kind: PersistentVolume
metadata:
  name: kanboard-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /home/jonathan/kanboard-app
