apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "name" . }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path