apiVersion: v1
kind: Service
metadata:
  name: {{ include "name" . }}
spec:
  selector:
    app: {{ include "name" . }}
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 9084
      targetPort: 80
  type: {{ .Values.service.type }}
