name: Linters

on:
  pull_request:
    branches: [ main ]

jobs:
  jshint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install jshint
        run: npm install -g jshint
      - name: Run jshint
        run: jshint ./assets/js/core ./assets/js/components
